project_id = "sboaeutgckyiwunfmxqp"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.indexnow]
    verify_jwt = false
  [functions.sitemap]
    verify_jwt = false
  [functions.get-paypal-client-id]
    verify_jwt = false
