// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function getPublicSupabase() {
  const env = globalThis.process?.env ?? {};
  const url = env.SUPABASE_URL;
  const key = env.SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) throw new Error("Supabase env not configured");
  return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the BF SUMA Royal supplement catalog by keyword. Returns matching active products with name, slug, price (KES), benefit, and stock status.",
  inputSchema: {
    query: z.string().describe("Keyword to match against product name, benefit, or description. Use empty string to list all."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = getPublicSupabase();
    const max = limit ?? 10;
    let q = supabase.from("products").select("name,slug,price,benefit,description,stock_quantity,sku").eq("is_active", true).limit(max);
    if (query.trim()) {
      const pattern = `%${query.trim()}%`;
      q = q.or(`name.ilike.${pattern},benefit.ilike.${pattern},description.ilike.${pattern}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch a single BF SUMA Royal product by its URL slug (e.g. 'arthroxtra'). Returns full description, price (KES), benefit, PV value, and stock.",
  inputSchema: {
    slug: z2.string().describe("Product slug as it appears in the URL after /product/.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = getPublicSupabase();
    const { data, error } = await supabase.from("products").select("name,slug,price,pv_value,benefit,description,image_url,stock_quantity,sku,is_active").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No product found for slug: ${slug}` }], isError: true };
    const url = `https://www.bfsumaroyal.com/product/${data.slug}`;
    return {
      content: [{ type: "text", text: JSON.stringify({ ...data, url }, null, 2) }],
      structuredContent: { product: { ...data, url } }
    };
  }
});

// src/lib/mcp/tools/list-wellness-hubs.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_wellness_hubs_default = defineTool3({
  name: "list_wellness_hubs",
  title: "List wellness hubs",
  description: "List all active wellness hub pages (health goal categories such as Joint Pain, Sleep & Recovery). Returns name, slug, and hero description.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = getPublicSupabase();
    const { data, error } = await supabase.from("wellness_hubs").select("name,slug,hero_title,hero_description").eq("is_active", true).order("display_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const hubs = (data ?? []).map((h) => ({ ...h, url: `https://www.bfsumaroyal.com/wellness/${h.slug}` }));
    return {
      content: [{ type: "text", text: JSON.stringify(hubs, null, 2) }],
      structuredContent: { hubs }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
var list_blog_posts_default = defineTool4({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published BF SUMA Royal blog posts. Returns title, slug, excerpt, and published date. Newest first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max posts to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = getPublicSupabase();
    const { data, error } = await supabase.from("blog_posts").select("title,slug,excerpt,published_at,featured_image").eq("status", "published").order("published_at", { ascending: false, nullsFirst: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const posts = (data ?? []).map((p) => ({ ...p, url: `https://www.bfsumaroyal.com/blog/${p.slug}` }));
    return {
      content: [{ type: "text", text: JSON.stringify(posts, null, 2) }],
      structuredContent: { posts }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bfsuma-royal-mcp",
  title: "BF SUMA Royal MCP",
  version: "0.1.0",
  instructions: "Tools for exploring the BF SUMA Royal wellness catalog. Use `search_products` to find supplements by keyword, `get_product` for full details of one product by slug, `list_wellness_hubs` for health-goal hub pages, and `list_blog_posts` for recent published articles. All prices are in KES.",
  tools: [search_products_default, get_product_default, list_wellness_hubs_default, list_blog_posts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
